version: '3.8'

services:
  hardhat:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    ports:
      - "8545:8545"  # Expose Hardhat's RPC port
    volumes:
      - contracts:/usr/src/app/frontend/src/contracts  # Map the shared volume to hardhat's contracts directory
    networks:
      - hardhat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - contracts:/usr/src/app/src/contracts  # Map the shared volume to ./contracts in the frontend service
    networks:
      - hardhat-network

volumes:
  contracts:
    driver: local  # Named volume to store and share contract files

networks:
  hardhat-network:
    driver: bridge
